### ISSUE TITLE
No module named 'imagecluster'

### ISSUE THREAD

**Issue by gaurav326913** [elcorto/imagecluster#8] opened 2019-03-12 06:12 UTC
Hi, I ran the first 2 lines of the code 
from imagecluster import calc as ic
from imagecluster import postproc as pp

and i get this error : ModuleNotFoundError: No module named 'imagecluster'. 

I checked the requirements doc, I have all the necessary packages. 

Please help.

**Comment by elcorto** [comment] 2019-03-12 11:17
Check #4. Also make sure you understand the ins and outs of [importing modules and packages](https://docs.python.org/3/tutorial/modules.html). Check pip's documentation as well, and maybe the examples [here](https://github.com/elcorto/samplepkg).

**Comment by gaurav326913** [comment] 2019-03-21 13:20
Thanks for the reply. followed your inputs, seems I am in the right track. 

However, I am facing the below error now, while running the example_main.py file. 

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Did a google search on the same, seems its due to server issue. I downloaded the weight file from the link "https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5" and placed it in the folder /users/.keras/models. Even after doing the above step, when i run the example_main.py file, it still tries to downloaded the weight file. 

Please help. 

Thanks

**Comment by elcorto** [comment] 2019-03-22 16:30
That sounds like a Keras+Windows issue then. You may have placed the file in the wrong directory such that Keras still doesn't find it. I don't know where Keras' model location is on Windows, sorry. On Linux & friends it is `$HOME/.keras/models`, as mentioned in the README. You may check the Keras documentation again.

**Comment by elcorto** [comment] 2019-03-29 11:15
I'm closing this since there has been no update since a week and the issue is not directly related to the code in this repo. Feel free to re-open this at any time in case I'm wrong, though :)

**Closed by elcorto** 2019-03-29 11:15 UTC
Labels: install
